name: model training 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          pip install soundfile
          
          

          

          
          
          echo "## Model metrics" > report.md
          cat metric.txt >> report.md
          cat notebooks/loss.txt >> report.md
          

          
          echo "## Data viz" >> report.md
          cml-publish Spectrogram.png --md >> report.md
          cml-publish plots/cleanwo.png --md >> report.md
          cml-publish plots/wordc.png --md >> report.md
          cml-publish plots/scatterlen.png --md >> report.md
          
          
          cml-send-comment report.md
